nickname: MailRules

BulkFolder: Bulk
SpamFolder: Junk

Rules:
    - subjectContains: Emailscript
      category: Emailscript
    - host: hai.com
      category: HAI
    - host: facebookmail.com
      category: Social
    - subjectContains: Jaiya
      category: friends
    - subjectContains: Ulysses
      category: friends

Categories:
    Emailscript:
        skipScan: true
        whitelist: true
        saveUnread: true
        inboxDays: 7
    HAI
        inboxMax: 5
        whitelist: true
    Notifications:
        inboxMax: 2
        whitelist: true
    Newsletters:
        inboxMax: 2
        whitelist: true
    Bulk:
        folderDays: 60
    Junk:
        folderDays: 45
        blacklist: true
    Social:
        inboxMax: 2
        whitelist: true
    friends:
        saveUnread: true
        inboxDays: 7
        whitelist: true
